replicaCount: 1
image:
  repository: DOCKER_USERNAME/devops-exam-app
  tag: develop
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8000

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false

autoscaling:
  enabled: false

httpRoute:
  enabled: false
