name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    env:
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      TF_VAR_spaces_access_id: ${{ secrets.SPACES_ACCESS_KEY }}
      TF_VAR_spaces_secret_key: ${{ secrets.SPACES_SECRET_KEY }}
      AWS_EC2_METADATA_DISABLED: "true"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Secrets
        run: |
          if [ -z "${{ secrets.DO_TOKEN }}" ]; then echo "DO_TOKEN is not set"; exit 1; fi
          if [ -z "${{ secrets.SPACES_ACCESS_KEY }}" ]; then echo "SPACES_ACCESS_KEY is not set"; exit 1; fi
          if [ -z "${{ secrets.SPACES_SECRET_KEY }}" ]; then echo "SPACES_SECRET_KEY is not set"; exit 1; fi

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="access_key=${{ secrets.SPACES_ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.SPACES_SECRET_KEY }}"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
